### ISSUE TITLE
Peticion calculadora Axie Tools.

### ISSUE THREAD

**Issue by pcenthusiast92** [jmarcosg/axieTools#18]
Hola bro como estas, queria preguntarte si habia posibilidad de que en tu calculadora de Axie tools

Pueda existir la posibilidad de tener una opcion para pasarse a la version antigua de la calculadora, es decir hasta la version que estaba el dia de ayer 22 noviembre 2021? ya que la nueva calculadora se complica el marcar doble cartas con el botoncito?

Algo asi que el jugador tenga en esa pagina una opcion para probar la antigua calculadora?

https://jmarcosg.github.io/axieTools/assets/pages/EN/index.html

**Comment by EderCB** [comment]
Espero que también habilitien esa misma opcion, se me hace muy raro la nueva interfaz

**Comment by jmarcosg** [comment]
Buenas! Hace unos momentos volví a poner esa versión. Pueden acceder a la misma a través del botón correspondiente en la barra de navegación.

Saludos cordiales!

![unknown](https://user-images.githubusercontent.com/57733635/143142169-1ef4d282-5e2d-4e22-ba84-4e500590c3ec.png)

**Comment by pcenthusiast92** [comment]
Perfecto gracias Jmarcosg, por cierto vi que la opcion de V1.0 te la da solo si pones la calculadora en español, si la pones en Ingles, no te da la opcion v1.0.

**Comment by jmarcosg** [comment]
Ahí lo volví a agregar, gracias por avisar! Se me olvidó de hacerlo en el momento de volver a agregar la V1.0
