### ISSUE TITLE
Sugerencia para el contador de cartas + calculador de daño

### ISSUE THREAD

**Issue by copperfield42** [jmarcosg/axieTools#22]
Hola amigo, podrías hacer que el contador de cartas de se ajuste junto con el contador de energía, ósea que cuando le des -1 energía también descuente una carta, para así no tener que presionar 2 botones para llevar la cuenta de ambos. También podría ser con un botón adicional, el usual y otro para contar cuando robas energía así no descuente cartas.

Otra cosa que también seria genial es una calculadora de daño, similar a [Flowbot44's Axie Infinity Extension](https://chrome.google.com/webstore/detail/flowbot44s-axie-infinity/iknjhcclpcildaklifghhjblmbjpkole), algo así como en una cajita donde metes los numeritos de ataque de tus cartas o la del rival y te dice más o menos cuanto le pegas a cada grupo de axies.

Gracias y buen día :)

**Comment by jmarcosg** [comment]
Muy buena sugerencia! La voy a estar implementando en el migrado a una mejor tecnología para el desarrollo del sitio 😊
